// GEOCODING=Process of converting adresses into geographic coordinates used to put a  marker on maps !
// GEOCODING API-AVAILABLE IN MAPBOX GEOCODING API  (FORWARD AMD BACKWARD TWO); 1_ LOCATION->COORDINATE  2)COORDINATEE->LOCATION (BACKWARD)

// MAPBOX-SDK  GEOJSON DATA IN  LISTING SCHEMAD